name: 'Create Issue'
description: 'Create Issue'
inputs:
  actor:
    description: 'Actor'
    required: true
  owner:
    description: 'Owner'
    required: true
  repo:
    description: 'Repository'
    required: true
  github_token:
    description: 'Github Token'
    required: true
  ref:
    description: 'Ref'
    required: true
  tag_name:
    description: 'Tag Name'
    required: true
  changelog:
    description: 'ChangeLog'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'