name: 'Update Issue'
description: 'Update Issue'
inputs:
  owner:
    description: 'Owner'
    required: true
  repo:
    description: 'Repository'
    required: true
  github_token:
    description: 'Github Token'
    required: true
  ref:
    description: 'Ref'
    required: true
  tag_name:
    description: 'Tag Name'
    required: true
  tests_result:
    description: 'Result of lint, unit and e2e tests'
    required: false
  tests_result_url:
    description: 'Url on result of lint, unit and e2e tests'
    required: false
  deploy_result:
    description: 'Result of deploy'
    required: false
  deploy_result_url:
    description: 'Url on result of deploy'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'