name: GitHub Actions on Release Tag

on: 
  push:
    tags:
      - 'v[0-9]+'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  jobs-result:
    environment:
      name: release
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, e2e-tests]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check results
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo ${{ github.repository_owner }}
          echo ${{ toJson(needs) }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.1
        id: changelog-ci
        with:
          config_file: changelog-ci-config.json
          release_version: "${{  github.ref_name }}"
      - name: Replace substring
        uses: mad9000/actions-find-and-replace-string@3
        id: changelog
        with:
          source: ${{ steps.changelog-ci.outputs.changelog }}
          find: '%0A'
          replaceAll: '\ '
      - name: Get Changelog Output
        id: get_changelog_output
        run: |
          echo "${{ steps.changelog.outputs.value }}"
          echo "${{ steps.changelog.outputs.value }}" >> $GITHUB_STEP_SUMMARY
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.get_changelog_output.outputs.changelog }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            "${{ steps.changelog.outputs.value }}"
            "${ steps.changelog.outputs.value }"
          draft: false
          prerelease: false